/**
 * Minesweeper 2020
 * REST API for the famous Minesweeper game
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Cell from './Cell';

/**
 * The Board model module.
 * @module model/Board
 * @version 0.0.1
 */
class Board {
    /**
     * Constructs a new <code>Board</code>.
     * @alias module:model/Board
     */
    constructor() { 
        
        Board.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Board</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Board} obj Optional instance to populate.
     * @return {module:model/Board} The populated <code>Board</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Board();

            if (data.hasOwnProperty('rowsCount')) {
                obj['rowsCount'] = ApiClient.convertToType(data['rowsCount'], 'Number');
            }
            if (data.hasOwnProperty('columnsCount')) {
                obj['columnsCount'] = ApiClient.convertToType(data['columnsCount'], 'Number');
            }
            if (data.hasOwnProperty('minesCount')) {
                obj['minesCount'] = ApiClient.convertToType(data['minesCount'], 'Number');
            }
            if (data.hasOwnProperty('cells')) {
                obj['cells'] = ApiClient.convertToType(data['cells'], [[Cell]]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} rowsCount
 */
Board.prototype['rowsCount'] = undefined;

/**
 * @member {Number} columnsCount
 */
Board.prototype['columnsCount'] = undefined;

/**
 * @member {Number} minesCount
 */
Board.prototype['minesCount'] = undefined;

/**
 * @member {Array.<Array.<module:model/Cell>>} cells
 */
Board.prototype['cells'] = undefined;






export default Board;

