/**
 * Minesweeper 2020
 * REST API for the famous Minesweeper game
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Cell model module.
 * @module model/Cell
 * @version 0.0.1
 */
class Cell {
    /**
     * Constructs a new <code>Cell</code>.
     * @alias module:model/Cell
     */
    constructor() { 
        
        Cell.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Cell</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Cell} obj Optional instance to populate.
     * @return {module:model/Cell} The populated <code>Cell</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Cell();

            if (data.hasOwnProperty('row')) {
                obj['row'] = ApiClient.convertToType(data['row'], 'Number');
            }
            if (data.hasOwnProperty('column')) {
                obj['column'] = ApiClient.convertToType(data['column'], 'Number');
            }
            if (data.hasOwnProperty('mine')) {
                obj['mine'] = ApiClient.convertToType(data['mine'], 'Boolean');
            }
            if (data.hasOwnProperty('revealed')) {
                obj['revealed'] = ApiClient.convertToType(data['revealed'], 'Boolean');
            }
            if (data.hasOwnProperty('flag')) {
                obj['flag'] = ApiClient.convertToType(data['flag'], 'String');
            }
            if (data.hasOwnProperty('minesAround')) {
                obj['minesAround'] = ApiClient.convertToType(data['minesAround'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} row
 */
Cell.prototype['row'] = undefined;

/**
 * @member {Number} column
 */
Cell.prototype['column'] = undefined;

/**
 * @member {Boolean} mine
 */
Cell.prototype['mine'] = undefined;

/**
 * @member {Boolean} revealed
 */
Cell.prototype['revealed'] = undefined;

/**
 * @member {module:model/Cell.FlagEnum} flag
 */
Cell.prototype['flag'] = undefined;

/**
 * @member {Number} minesAround
 */
Cell.prototype['minesAround'] = undefined;





/**
 * Allowed values for the <code>flag</code> property.
 * @enum {String}
 * @readonly
 */
Cell['FlagEnum'] = {

    /**
     * value: "QUESTION_MARK"
     * @const
     */
    "QUESTION_MARK": "QUESTION_MARK",

    /**
     * value: "RED_FLAG"
     * @const
     */
    "RED_FLAG": "RED_FLAG"
};



export default Cell;

