/**
 * Minesweeper 2020
 * REST API for the famous Minesweeper game
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Board from './Board';

/**
 * The Game model module.
 * @module model/Game
 * @version 0.0.1
 */
class Game {
    /**
     * Constructs a new <code>Game</code>.
     * @alias module:model/Game
     */
    constructor() { 
        
        Game.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Game</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Game} obj Optional instance to populate.
     * @return {module:model/Game} The populated <code>Game</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Game();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('board')) {
                obj['board'] = Board.constructFromObject(data['board']);
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'Date');
            }
            if (data.hasOwnProperty('modified')) {
                obj['modified'] = ApiClient.convertToType(data['modified'], 'Date');
            }
            if (data.hasOwnProperty('outcome')) {
                obj['outcome'] = ApiClient.convertToType(data['outcome'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Game.prototype['id'] = undefined;

/**
 * @member {String} username
 */
Game.prototype['username'] = undefined;

/**
 * @member {module:model/Board} board
 */
Game.prototype['board'] = undefined;

/**
 * @member {Date} created
 */
Game.prototype['created'] = undefined;

/**
 * @member {Date} modified
 */
Game.prototype['modified'] = undefined;

/**
 * @member {module:model/Game.OutcomeEnum} outcome
 */
Game.prototype['outcome'] = undefined;





/**
 * Allowed values for the <code>outcome</code> property.
 * @enum {String}
 * @readonly
 */
Game['OutcomeEnum'] = {

    /**
     * value: "LOST"
     * @const
     */
    "LOST": "LOST",

    /**
     * value: "WON"
     * @const
     */
    "WON": "WON"
};



export default Game;

