/**
 * Minesweeper 2020
 * REST API for the famous Minesweeper game
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GameCreationData model module.
 * @module model/GameCreationData
 * @version 0.0.1
 */
class GameCreationData {
    /**
     * Constructs a new <code>GameCreationData</code>.
     * @alias module:model/GameCreationData
     * @param username {String} 
     */
    constructor(username) { 
        
        GameCreationData.initialize(this, username);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, username) { 
        obj['username'] = username;
    }

    /**
     * Constructs a <code>GameCreationData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GameCreationData} obj Optional instance to populate.
     * @return {module:model/GameCreationData} The populated <code>GameCreationData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GameCreationData();

            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('rowsCount')) {
                obj['rowsCount'] = ApiClient.convertToType(data['rowsCount'], 'Number');
            }
            if (data.hasOwnProperty('columnsCount')) {
                obj['columnsCount'] = ApiClient.convertToType(data['columnsCount'], 'Number');
            }
            if (data.hasOwnProperty('minesCount')) {
                obj['minesCount'] = ApiClient.convertToType(data['minesCount'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} username
 */
GameCreationData.prototype['username'] = undefined;

/**
 * @member {Number} rowsCount
 */
GameCreationData.prototype['rowsCount'] = undefined;

/**
 * @member {Number} columnsCount
 */
GameCreationData.prototype['columnsCount'] = undefined;

/**
 * @member {Number} minesCount
 */
GameCreationData.prototype['minesCount'] = undefined;






export default GameCreationData;

